exercises/concept/translation-service imports and a minor typo
exercism/javascript pull request #1644
Opened 2022-01-29 15:20 UTC by kroitor

Without those imports, the tests will always fail if you attempt to catch those errors. On the JavaScript track, the concept of importing is not introduced before this exercise, so it makes sense to add those imports into the JS template for less confusion.

Also a minor typo in the instructions.

2022-01-29 15:23 UTC, kroitor commented
The failing check is not related to this PR, it is most likely an intermittent dependency issue.

2022-01-30 14:35 UTC, junedev requested changes
This is a good point you are making regarding the imports. However, there is an issue with consistency know and also there seems to be some general issue with the exercise. Maybe you can help to shed some light on this.

Currently, the exemplar solution passes all the tests without these imports. Even student solutions import the errors but then don't end up using them.
Examples:
- https://exercism.org/tracks/javascript/exercises/translation-service/solutions/m42dax
- https://exercism.org/tracks/javascript/exercises/translation-service/solutions/Elmaletas

I don't fully understand why this is. Maybe the test cases are not good enough here, maybe not checking for the specific errors is really the better solution, maybe there is some bug related to the importing (see https://github.com/exercism/javascript/issues/1549) that keeps students from using the import. :thinking: 

In any case, if you feel like a good solution to this exercise should import (and use) those errors, then please adjust the exemplar.js file accordingly. Currently the stub and the exemplar don't match up anymore. The exemplar file is shown to the mentors as "reference solution" for concept exercises, that is why it is important it fits.

2022-01-30 21:21 UTC, kroitor commented
@junedev i'll do my best to change the exemplar, but, as you've noted, the reference solution doesn't use those imports. This entire exercise was the most confusing so far on my JS track, which is partially due to incomplete instructions, and partially due to those error imports. Without those imports this iteration would not build: 

- https://exercism.org/tracks/javascript/exercises/translation-service/iterations

I think, the tests for this exercise are lacking an edge case, where the user should not call `api.request` if the resource is known to be `Untranslatable` from `api.fetch` right away. If we add that edge case to the test, the existing exemplar will fail, cause it sends an api.request on all failures. Which is why I think the exemplar is wrong, despite that it satisfies the tests.

2022-02-01 21:04 UTC, junedev commented
@kroitor Thanks for you advice on what's wrong with the exercise. Given that information, I will merge this PR as is and create a new issue for adding the missing test case and fixing the examplar solution. Feel free to pick up that issue as well in case you are interested in working on it.

The link you posted only works for you but I found the code you wanted to show on your public profile: https://exercism.org/tracks/javascript/exercises/translation-service/solutions/kroitor

2022-02-01 21:04 UTC, junedev approved these changes

2022-02-01 21:05 UTC, merged