fix: change story website to non-existant destination
exercism/javascript pull request #2317
Opened 2023-11-12 16:14 UTC by vaeng

See: https://forum.exercism.org/t/ad-link-in-lucky-numbers-exercise/8204/2

2023-11-12 18:56 UTC, neenjaw approved these changes

2023-11-12 18:57 UTC, neenjaw commented
@vaeng I think you'll need @iHiD or @ErikSchierboom to approve this one.  Not sure how available the core js maintainers are at the moment

2023-11-12 19:54 UTC, kotp requested changes
We could use the established imaginary (yet real) provided example standard, such as `https://fun-with-numbers.example.com` instead.

2023-11-12 19:54 UTC, kotp commented on exercises/concept/lucky-numbers/.docs/instructions.md
> +He has a small website for playing around with numbers: www.kojo-presents-fun-with-numbers.com.
Why would we have a link that goes nowhere?  It is not guaranteed to go nowhere and may need to be changed later.

2023-11-12 21:25 UTC, vaeng commented
Maybe it is best to just drop the url. it does not add to the exercise at all.

2023-11-14 11:47 UTC, ErikSchierboom approved these changes

2023-11-14 11:48 UTC, merged