destructure parameters
exercism/javascript pull request #2507
Opened 2024-07-13 01:52 UTC by ConeDragon

https://forum.exercism.org/t/js-elyses-destructured-enchantments-exemplar-inconsistent/12084

2024-07-13 01:53 UTC, ConeDragon commented
In exercise notes, should there be a note that destructuring in the function itself is also acceptable?

2024-07-13 12:44 UTC, SleeplessByte commented
> In exercise notes, should there be a note that destructuring in the function itself is also acceptable?

That would be good. If you mentor this exercise it's a good opportunity to inform a student that in JavaScript you can do it directly in the parameter.

2024-07-13 12:45 UTC, SleeplessByte requested changes

2024-07-13 12:45 UTC, SleeplessByte commented on exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js
> +export function discardTopCard([first, ..rest]) {
Missing a `.` as it should be `...`

2024-07-13 20:01 UTC, ConeDragon commented on exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js
> +export function discardTopCard([first, ..rest]) {
Whoops! Sorry

2024-07-24 12:01 UTC, SleeplessByte approved these changes
Thank you!

2024-07-24 12:01 UTC, merged