Improve Forth test
exercism/javascript pull request #892
Opened 2020-11-16 12:07 UTC by tgujar

The original version of the test only checks for positive numbers.

`
if(/^\d*$/.test(functionName)) throw new Error("Invalid definition");
`

An implementation like above will work for positive numbers, but not for negative numbers.

2020-12-16 20:46 UTC, SleeplessByte commented
/format

2020-12-16 20:53 UTC, SleeplessByte requested changes
Hi there! Thank you for your work.

The test you've proposed to change is listed [here](https://github.com/exercism/javascript/blob/5d7e07d4b7c8fa36ed4a4b5b173f805c9e6ab2d1/exercises/forth/.meta/tests.toml#L117-L118):
```toml
# cannot redefine numbers
"35958cee-a976-4a0f-9378-f678518fa322" = true
```

It means it's sourced from [`exercism/problem-specifications`](https://github.com/exercism/problem-specifications), and indeed can be found [here](https://github.com/exercism/problem-specifications/blob/master/exercises/forth/canonical-data.json#L429-L437): 

```json
{
  "uuid": "35958cee-a976-4a0f-9378-f678518fa322",
  "description": "cannot redefine numbers",
  "property": "evaluate",
  "input": {
    "instructions": [": 1 2 ;"]
   },
   "expected": {"error": "illegal operation"}
},
```

Instead of merely _updating_ the test we have, we should **add** a new test and also open a PR to `problem-specifications` so _other tracks_ can benefit from your insight.

1. generate a _new_ unique uuid, for example using an online generator or `configlet uuid` if you have `configlet` (see `CONTRIBUTING.md`)
2. add the new test and move your change into this new test
3. add the new test to `.meta/tests.toml` (you'll need the uuid now)
4. open a PR on `exercism/problem-specifications` with the same uuid, input and expected output.

2021-02-24 14:58 UTC, SleeplessByte commented
@tgujar is this something you could do for us <3? If not, that's okay, but please let us know so we can take action instead.

2021-02-24 15:18 UTC, tgujar commented
Oop I forgot about this, will get it done

2021-02-26 13:15 UTC, tgujar commented
Here's the [PR](https://github.com/exercism/problem-specifications/pull/1787) in [`exercism/problem-specifications`](https://github.com/exercism/problem-specifications). I have added the UUID to `.meta/tests.toml`

2021-04-02 16:26 UTC, SleeplessByte commented
(can you rebase?)

2021-04-02 18:59 UTC, tgujar commented
I am not quite sure how to proceed since the files were moved. Should I create a new commit?

2021-04-02 20:39 UTC, SleeplessByte commented
Eh. Good question. This is what you can do!

```
git mv exercises/forth exercises/practice/forth
```

Commit that, THEN rebase. If you can't work it out, I will do it for ya, no problem!

2021-04-03 12:48 UTC, tgujar commented
Thank you for the suggestion, I did manage to rebase my branch. I however ended up affecting two other files when I did not intend to. Unfortunately I only realized this after I had already pushed to remote. I tried to recover from there but the only solution I found was to reset to a previous commit(hope that's alright)

2021-04-03 13:33 UTC, SleeplessByte approved these changes

2021-04-03 13:33 UTC, merged

2021-04-03 13:34 UTC, SleeplessByte commented
Looks great @tgujar, than you a million.

If you wish, you can PR yourself into [this list](https://github.com/exercism/javascript/blob/main/exercises/practice/forth/.meta/config.json#L4-L9). I forgot to mention it before (it's super new) but I want you to be able to have the credit for improving this exercise.